class SessionsController < ApplicationController
    def new
    end
    def create
        @user=User.find_by_email params[:email]
        if @user && @user.authenticate(params[:password])

            # .autheticate method was generated by / with has_secure_password method. This method takes a password and hashes it in the same was as it was hashed first time and compares the the outcome with the password stord in password_digest. It returns true if password hash is matched else false
            session[:user_id]=@user.id
            # The session is an object usable in controllerthat uses cookies to store
            # encrypted data. To Sign in a user, we stor their user_id in the session for later use
            redirect_to root_path, notice: "Logged in"
        else
            flash[:alert]="Wrong email or password"
            render :new
        end
    end
    def destroy
        session[:user_id]=nil # By replacing value of user_id in session with nil we made out user logged out
        redirect_to root_path, notice: "Logged Out!"
    end
end
