class WelcomeController < ApplicationController
  # This controller is called welcome
  # This file was generated by running the command:
  # > rails g controller welcome
  # The above command also created a directory "/app/views/welcome"

  # inside of the controller every instance method is called a action
  def index # index action
    # By default rails will render a template within 
    # a folder that has the controller name
    # using the file that matches the action name
    # -> this action will render out the file at "/views/welcome/index.html.erb"
  end

  def goodbye
    
  end
end
